### ISSUE TITLE
Namespace not specified issue in flutter 3.27.0

### ISSUE THREAD

**Issue by patthipati** [pikaju/flutter-maps-launcher#53] opened 2024-12-12 18:09 UTC
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':maps_launcher'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

**Comment by cyclotron3k** [comment] 2024-12-15 05:09
Duplicate of #44

**Comment by pikaju** [comment] 2024-12-27 16:46
Hey, sorry for the wait. This problem should be fixed in 3.0.0, could you check if it works? If not, please open another issue.

**Closed as completed by pikaju** 2024-12-27 16:46 UTC
